### ISSUE TITLE
Add CSV headers

### ISSUE THREAD

**Issue by KlausBrunner** [KlausBrunner/solarpos#2]
For CSV output, it would be useful to get an (optional) header row.

**Comment by piyush280599** [comment]
@KlausBrunner Can you please assign me this issue? I'm new to open source and would like to contribute in this. Any reply would be appreciated!

**Comment by KlausBrunner** [comment]
Hi, thanks for your interest. Feel free to work on this as you please, and then just submit a [pull request](https://docs.github.com/en/pull-requests) - no need for assignment.
