### ISSUE TITLE
Set up proper release/distribution process

### ISSUE THREAD

**Issue by KlausBrunner** [KlausBrunner/solarpos#5]
Now that this thing is becoming somewhat useful, a proper release process should be set up to easily get releases done.

Publishing to a Maven repo isn't a priority for a CLI app, but nicely packaged distributions in a couple of formats (single JAR, Homebrew, etc.) would make sense. Perhaps build GraalVM native images as well if feasible on GitHub.

Jreleaser handles the git tagging and distribution part, but does not seem to do the POM changes that Maven's release plugin does. May need to combine those.

**Comment by aalmiray** [comment]
Hi there! JReleaser author here 😄 That's correct, the tool does not (currently) manage nor update the project's version. You'll have to keep using the chosen build tool for that, in this case Maven. Use either the release or versions plugins depending of your preference.

**Comment by KlausBrunner** [comment]
> Hi there! JReleaser author here 😄 That's correct, the tool does not (currently) manage nor update the project's version. You'll have to keep using the chosen build tool for that, in this case Maven. Use either the release or versions plugins depending of your preference.

Hey, thanks for chiming in! I'll look into it. BTW, this might be a good addition to the docs/samples of JReleaser. I suspect it's a common situation for those using Maven builds.

**Comment by aalmiray** [comment]
That's right, a guided example of how to use the `versions` plugin alongside JReleaser sounds like a good idea.

**Comment by KlausBrunner** [comment]
@aalmiray just as quick feedback, I **love** that JReleaser comes with its own built in ["assemble Java archive" thing](https://jreleaser.org/guide/latest/reference/assemble/java-archive.html). Both the standard Maven assembly plugin as well as the appassembler plugin are a real hassle to get working with shaded JARs, and this thing just does it out of the box!

**Comment by KlausBrunner** [comment]
Basic process in place, but more work needed to collect the various artefacts and create a single release from all.

**Comment by aalmiray** [comment]
Perhaps kcctl may serve as inspiration https://github.com/kcctl/kcctl

**Comment by KlausBrunner** [comment]
> Perhaps kcctl may serve as inspiration https://github.com/kcctl/kcctl

Thanks, it certainly helps, but it's pretty complex too. I'm really trying to keep the config as minimal as possible. I'm using the nativeImage assembler, running a matrix build action for Linux/MacOS/Win, and collecting all the artefacts (well, the entire target folder) in one place in the next job. This works as expected. My naive idea was that a jreleaser:full-release would then pick up all the platform-specific archives it finds, but it doesn't work that way - it only picks up the "current OS" one and ignores the other two. Is there an easy way to achieve a sort of "take all the assemblies/distros you find" without a lot of config in the POM or action? I'd find it quite convenient to specify the built architectures only in one place.

**Comment by aalmiray** [comment]
Sadly no, not at the moment. All platform specific artifacts must be defined explicitly for the time being.
Perhaps and additional option may be added to the assembler to let it know other artifacts may be available during artifact resolution

jlink does it ->  https://github.com/jreleaser/jreleaser/blob/main/core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/assemble/JlinkAssemblerResolver.java
nativeImage does not -> https://github.com/jreleaser/jreleaser/blob/main/core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/assemble/NativeImageAssemblerResolver.java

**Comment by aalmiray** [comment]
Filed https://github.com/jreleaser/jreleaser/issues/1196

**Comment by KlausBrunner** [comment]
Good enough for now, closing.

- Named releases could be automated a little more (currently using the Maven release plugin on my machine to do all the POM updates and tags before manually triggering a Github action). Not a big deal.
- Native image assembly config is still a bit non-elegant, but perhaps this will be helped by the next JReleaser version. 
- Might add a homebrew tap in future.
